version: "3.9"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"


volumes:
  influxdb_data:
  grafana_data:
